FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests plotly pillow


COPY frontend/ ./frontend/

# Expose port
EXPOSE 8501

# Run Streamlit
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]