stages:
  prepare:
    cmd: python src/pipeline/prepare.py
    deps:
      - src/pipeline/prepare.py
      - data/raw
    outs:
      - data/v1_resized
    params:
      - data.raw_dir
      - data.v1_dir
      - data.classes

  transform:
    cmd: python src/pipeline/transform.py
    deps:
      - src/pipeline/transform.py
      - data/v1_resized
    outs:
      - data/v2_augmented
    params:
      - data.v1_dir
      - data.v2_dir
      - data.img_size
      - data.random_seed
      - data.classes

  train_baseline:
    cmd: python -u src/training/train_baseline_cnn.py
    deps:
      - src/training/train_baseline_cnn.py
      - data/v1_resized
    outs:
      - models/artifacts/baseline_cnn_best.pth
    metrics:
      - models/artifacts/metrics_baseline_cnn.json:
          cache: false
    params:
      - train.batch_size
      - train.epochs
      - train.learning_rate
      - train.early_stopping_patience
      - data.v1_dir
      - data.img_size

  train_mobilenet:
    cmd: python -u src/training/train_mobilenet.py
    deps:
      - src/training/train_mobilenet.py
      - data/v2_augmented
    outs:
      - models/artifacts/mobilenetv2_best.pth
    metrics:
      - models/artifacts/metrics_mobilenet.json:
          cache: false
    params:
      - train.batch_size
      - train.epochs
      - train.learning_rate
      - train.early_stopping_patience
      - data.v2_dir
      - data.img_size

  train_efficientnet:
    cmd: python -u src/training/train_efficientnet.py
    deps:
      - src/training/train_efficientnet.py
      - data/v2_augmented
    outs:
      - models/artifacts/efficientnet_best.pth
    metrics:
      - models/artifacts/metrics_efficientnet.json:
          cache: false
    params:
      - train.batch_size
      - train.epochs
      - train.learning_rate
      - train.early_stopping_patience
      - data.v2_dir
      - data.img_size

  train_svm:
    cmd: python -u src/training/train_svm.py
    deps:
      - src/training/train_svm.py
      - data/v2_augmented
    outs:
      - models/artifacts/svm_model.pkl
    metrics:
      - models/artifacts/metrics_svm.json:
          cache: false
    params:
      - data.v2_dir
      - data.classes

  train_mlp:
    cmd: python -u src/training/train_mlp.py
    deps:
      - src/training/train_mlp.py
      - data/v2_augmented
    outs:
      - models/artifacts/mlp_best.pth
    metrics:
      - models/artifacts/metrics_mlp.json:
          cache: false
    params:
      - train.batch_size
      - train.learning_rate
      - data.v2_dir
      - data.classes

  evaluate:
    cmd: python -u src/pipeline/evaluate.py
    deps:
      - src/pipeline/evaluate.py
      - models/artifacts/mobilenetv2_best.pth
      - data/v2_augmented/Testing
    outs:
      - eval/confusion_matrix.csv
    params:
      - data.v2_dir
      - data.classes
      - data.img_size